server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=health
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL91Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: classpath:templates/
      suffix: .html
